language: php
php:
  - 5.5
  - 5.4
  - hhvm

env:
  - TEST_DIR=tests

  before_install:
  - mysql -e "create database IF NOT EXISTS test;" -uroot

script: cd $TEST_DIR && phpunit Test.php && phpunit Database_Test.php
# script: phpunit tests/Test.php